/*
	--------------------------------
	-------- SQL Functions ---------
	--------------------------------
	
	UPPER / LOWER
	LTRIM / RTRIM / TRIM
	CONCAT / CONCAT_WS
	SUBSTRING
	REPLACE
	FLOOR / CEILING / ROUND
	DATEADD
	DATEDIFF
	DATEPART
	EOMONTH

	CONVERT / CAST
	CURRENT_TIMESTAMP / GETDATE
	
*/

-- UPPER / LOWER 
SELECT 
	PERSONEL_ADI,
	UPPER(PERSONEL_SOYADI) AS PERSONEL_ADI_BUYUKHARF
FROM PERSONEL


-- LTRIM / RTRIM / TRIM
SELECT 
	PERSONEL_ADI,
	PERSONEL_SOYADI,
	LTRIM(PERSONEL_ADI) AS PERSONEL_ADI_LTRIM,
	RTRIM(PERSONEL_ADI) AS PERSONEL_ADI_RTRIM,
	TRIM(PERSONEL_ADI) AS PERSONEL_ADI_RTRIM
FROM PERSONEL

-- CONCAT / CONCAT_WS
SELECT
	PERSONEL_ADI, 
	PERSONEL_SOYADI,
	CONCAT(PERSONEL_ADI, '&', PERSONEL_SOYADI, '&', IL_ADI, '&', DEPARTMAN_ADI) AS PERSONEL_ADI_SOYADI,
	
	CONCAT_WS('&',PERSONEL_ADI, PERSONEL_SOYADI, IL_ADI, DEPARTMAN_ADI) AS PERSONEL_ADI_SOYADI_CONCATWS
FROM PERSONEL


-- SUBSTRING
SELECT PERSONEL_ADI, PERSONEL_SOYADI, SUBSTRING(PERSONEL_ADI, 1, 3) AS XX FROM PERSONEL

-- REPLACE
SELECT PERSONEL_ADI, PERSONEL_SOYADI, REPLACE(PERSONEL_ADI, 'SERTAN', 'AHMET') AS XX FROM PERSONEL

-- FLOOR / CEILING / ROUND
SELECT
	FLOOR(24.9) AS FLOOR_COLUMN,
	CEILING(24.9) AS CEILING_COLUMN,
	ROUND(24.956, 3) AS ROUND_COLUMN_3,
	ROUND(24.956, 2) AS ROUND_COLUMN_2,
	ROUND(24.956, 1) AS ROUND_COLUMN_1,
	ROUND(24.956, 0) AS ROUND_COLUMN_0, 
	ROUND(24.956, 1, 0) AS ROUND_COLUMN_OVER, -- TRUNCATE
	ROUND(24.956, 1, 1) AS ROUND_COLUMN_TRUNC -- TRUNCATE
	--ROUND(24.956, 0, 1) AS ROUND_COLUMN_0  -- TRUNCATE

-- DATEADD
SELECT 
	GETDATE() AS NOW_DATE,
	DATEADD(DAY, 1, GETDATE()) AS NEW_DATE1,
	DATEADD(MONTH,1,GETDATE()) AS NEW_DATE2,
	DATEADD(YEAR,-10,GETDATE()) AS NEW_DATE3

-- DATEDIFF
SELECT 
	CURRENT_TIMESTAMP AS NOW_DATE,
	DATEDIFF(DAY,'2021-05-01', GETDATE()) AS DIFF


-- DATEPART
SELECT 
	CURRENT_TIMESTAMP AS NOW_DATE,
	DATEPART(YEAR,CURRENT_TIMESTAMP) AS NEW_DATE,

	YEAR(CURRENT_TIMESTAMP) AS NEW_DATE,

	DAY(CURRENT_TIMESTAMP) AS NEW_DATE

-- EOMONTH
SELECT 
	GETDATE() AS NOW_DATE,
	EOMONTH(GETDATE(),2) AS NEW_DATE
